version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - frontend
    networks:
      - wiznet
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    networks:
      - wiznet
networks:
  wiznet:
    driver: bridge
